### ISSUE TITLE
Writing up the roadmap for 0.2.0

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#11]
Elba finally reached it's first release, what a great news! Elba has become the first pacakge manager for idris that actually works! Next, we need to make elba more productive in the later work. So we've to write up a roadmap to guide us for it.

I'll write down some of my thoughts first.

- The name `elba`.
  I guess the name comes from the actor `Idris Elba`, right? This is a funny name to be like a 'action code' in development, but it blocks us to make it widely adopted in Idris world. Some of my friends expressed their feeling that "it sounds strange" for the first time to hear it to be the name of a pm. Additionally, when you google 'idris elba', you're likely to get the result of a male actor rather than a new pacakge manager you've heard from Reddit.

- Improve cli logging.
  Nothing more to say; you know, it just needs to be improved before anybody tries it for the first time. And I'd like to make efforts in this area.

- Setup an index.
  We've to make a workable index, at least a testing version.

- Out-of-box experience for user.
  One of the good points of Rust I love is it's priciple that `convention over configuration`, it lets me start trying out Rust right after I install it by rustup, without any configuration. I wish we can provide such an experience to users that they can start playing around elba just after one or two steps to install it.

**Comment by dcao** [comment]
- Setting up a new default index is the easiest of the tasks you've mentioned I think; I could do that now, and push a patch release to set the new index as the default.

- I agree with you that we need to improve command-line logging, both with regards to the pretty output for the users and our debug logging using `slog`, and that there's definite room for improvement for improving the out-of-the-box experience for first-time users (maybe by standardizing test/source directories like cargo does).

- With regards to the name, while we could change it to something more utilitarian like `ipack` or something, I think `elba` is a very memorable name which stands out, and my circumstantial evidence based on reddit replies to my comments on the "What are you working on" posts seems to indicate that people find the name funny and catchy.

  Even though the name might sound "weird" to some, as people use it more and more this becomes less of a problem. In any case, this wouldn't be the first time a package manager has a "weird" name: `leiningen` is named after a character in a book, I'm not sure what `pip` means, etc.

  With regards to SEO, people would just search for `idris elba package manager` and they would get what they're looking for, so it doesn't seem like too big of a deal.

My plan for now is to move this project to its own organization, create a new default index, and announce it to the world so that we can get some users and more feedback for a 0.2.0 release.

**Comment by andylokandy** [comment]
Yeah, so let's get started.

**Comment by andylokandy** [comment]
To be honest, I've got used to it... But I can imagine that every newcomer will always complains about it, and then gets used to it...

**Comment by dcao** [comment]
True, I might just be overthinking the problem.

I'll leave this issue open for a bit in case we need to take any action.
