### ISSUE TITLE
Prevent dependency chain breakage

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#22]
Package in elba can not be removed so that no dependency chain breakage can happen like that on npm. But how do we prevent the breakage when a git repo referred from index becomes unavailable? Cargo does not have this problem since it hosts the source file itself.

**Comment by dcao** [comment]
Ultimately the answer is there's nothing we can do to prevent breakage if a package becomes unavailable; that's completely out of our control.

The long-term solution to this is with the New Package Management Experience(tm), where we'll have a proper website and a standardized "package repo" format for uploading tarballs of packages like Cargo/crates.io instead of just linking to git repositories; the git repo solution is just temporary.

**Comment by andylokandy** [comment]
Got it. (・∀・)b
