### ISSUE TITLE
Elba is unusable when offline

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#23]
Elba would stuck at the steps of retrieving index or other packages that are already retrieved into cache when the connection is unstable or even disconnected. Even though I have good connection speed, elba still spends a lot of time at retrieving step when I just want to re-compile some little tweaks.

**Comment by dcao** [comment]
- The introduction of the `--offline` flag, along with shortening the timeout for package downloads, in the latest commit has mostly mitigated this issue.

- I still can't figure out how to reduce the timeout for fetching from a git repo; help there would be appreciated!

**Comment by andylokandy** [comment]
One solution could be moving fetch operation out of main thread so that we can call `wait_timeout()` on it.

**Comment by andylokandy** [comment]
IMO, keep syncing the latest head of git is not an expected behavior. On the contrary, the latest commit should also be locked and we should not touch it until user runs `elba update`.

**Comment by andylokandy** [comment]
If we only fetch index when we have new packaged reqested plus the lock of commit, the offline flag is no longer needed, I think.

**Comment by andylokandy** [comment]
Need any help in implementation? I can start to work on a PR.

**Comment by dcao** [comment]
- Even if we pin our git repositories to a certain commit and only update on an `elba update` invocation, I think it's still worth keeping the `--offline` flag, since it changes how elba's resolution algorithm works (it temporarily replaces all direct resolutions in package indices with their counterparts in the local cache).

**Comment by andylokandy** [comment]
> since it changes how elba's resolution algorithm works (it temporarily replaces all direct resolutions in package indices with their counterparts in the local cache)

I think this should only affect the packages that are not already locked, and building a package that already has a lockfile that matches the DepReq should not perform any network operations, right?

**Comment by dcao** [comment]
The functionality of the offline flag is meant to implement what Cargo calls ["airplane mode"](https://github.com/rust-lang/cargo/issues/4686). It shouldn't violate lockfile guarantees, but it will change how elba's dependency resolution strategy works:

  - If the lockfile is valid for a certain package and the package which the lockfile points to is stored on-disk, elba will use that package regardless of if `--offline` is passed or not.

  - If no valid lockfile exists (either because there simply is no lockfile or because the lockfile is incompatible with the current manifest's requirements) for a certain package, the dependency resolution algorithm will kick in for when choosing the "best" version of that package:
    
    - With `--offline` disabled, elba will just choose the highest version of the package available from the package index.

    - With `--offline` enabled, elba will choose the highest version of the package *which is already available in the global cache*, thereby skipping all of the downloading that would be necessary if `--offline` were disabled.

So yes, this change in the algorithm would only affect packages which are not locked or have an outdated version in the lockfile.

**Comment by dcao** [comment]
With regards to git resolutions, for now I'm going to keep the behavior as-is: if a user specifies that they want the master branch of a git repository in their manifest, elba will assume that the user wants to keep that repository as up-to-date as possible; if they want to pin the repo to a specific tag or commit, they can do that themselves in the manifest.

**Comment by dcao** [comment]
Update: I think I've found a way to get proper git pinning to work!

The problem I was having before was how to reflect changes in the manifest in the lockfile; my naive solution before was unable to reflect changes to git dependencies in the manifest in a lockfile, so I deemed it as a subpar solution and chose to stick with what we were doing before. However, I've now figured out a workable solution.

The rules for git dependencies are as follows:

  - If a manifest specifies a branch, the locked commit in the lockfile must be a commit on that branch.

    - If the commit in the lockfile is not on the branch or the lockfile doesn't exist, elba will choose the latest commit on that branch and lock it.

  - If a manifest specifies a tag or a commit, the locked commit in the lockfile must correspond to that tag/commit.

**Comment by andylokandy** [comment]
After rewiewing the code, I've found that even though a valid lockfile exists, elba still fetches the index unconditionally.

**Comment by dcao** [comment]
Yeah, we still update the index during every invocation of a build command. This shouldn't be too much of an issue with the `--offline` flag, though

**Comment by andylokandy** [comment]
But it slows down the rapid code-build-test iteration. It's annoying to always wait for a few seconds to sync the index for no purpose.

**Comment by dcao** [comment]
This has been fixed with the latest commit, along with some bug fixes for git resolutions.
