### ISSUE TITLE
Question - binary target that depends on its own library target

### ISSUE THREAD

**Issue by andrevidela** [elba/elba#61]
Hi,

I have a project with an elba manifest that has two binaries and one library target. I would like the binary targets to make use of its own library target as a dependency. I was unable to find anything about this use-case in the documentation, is it a supported use-case? If not, how can I work around it?

**Comment by dcao** [comment]
If you place the bins and lib in the same source directory, you should be able to get what you're going after.

**Comment by clayrat** [comment]
@dcao we ran into this issue where our `Main` module is in a subfolder `Foo` but the `ibc`s it depends are in the parent folder, which leads to the following error at the backend invocation stage:

```
> "idris" "-o" "baz" "--codegen" "c" "-p" "contrib" "-i" "target/build/bin/Foo" "target/build/bin/Foo/Main.ibc"
idris: erasure checker: unknown reference: Bar.bar
CallStack (from HasCallStack):
  error, called at src/Idris/Erasure.hs:363:21 in idris-1.3.1-13MvVmXYE33611bG6k1vOz:Idris.Erasure
```
(where `Bar` is a module residing in the parent folder)

If I run this command manually but removing the last part on the `-i` folder, it succeeds:
`idris -o baz --codegen c -p contrib -i target/build/bin target/build/bin/Foo/Main.ibc`

As far as I can see, this behavior is assumed in this line:
https://github.com/elba/elba/blob/master/src/lib/build/invoke.rs#L119

Is this intentional or should it rather be pointing to a folder corresponding to the one specified as `path` of the corresponding `[[targets.bin]]` section?

**Comment by andylokandy** [comment]
If I don't get it wrong, ibc will not depend on any other ibcs.

**Comment by clayrat** [comment]
@andylokandy Yes, note that this happens at the codegen stage, when the ibcs are already produced. It's the erasure checker that needs this information.

**Comment by andylokandy** [comment]
Ok. Now I figured out what's happening on typedef. I think this is the intended behavior, as `Main.idr` is in a subfolder it's also considered in the submodule, and because of that, it can't access the outer modules.

We may have chance to improve the error information some how.

**Comment by andylokandy** [comment]
>  should it rather be pointing to a folder corresponding to the one specified as path of the corresponding `[[targets.bin]]` section?

This is not going to work because we have no way to prevent the lib target importing the 'deep hidden' `Main.idr`. Allowing to redirect the dependency flow would cause other problems.

**Comment by andylokandy** [comment]
@clayrat I'm sorry, this is a bug. It's going to be fixed.
