### ISSUE TITLE
[[backend]] section in elba.toml is not being used

### ISSUE THREAD

**Issue by mixedCase** [elba/elba#68]
I tried to get the following small hello world project to compile using the javascript backend, but `elba build` exits with:

```
$ LC_ALL=C elba build
       [1/2] Resolving dependencies...
       [2/2] Building targets...
    Building test/test 0.1.0 (dir+/mnt/DataHDD/code/sw/test) [94371529..]
     [error] Couldn't build binary 0 for test/test 0.1.0 (dir+/mnt/DataHDD/code/sw/test)
couldn't locate codegen output file: /mnt/DataHDD/code/sw/test/target/bin/test.js

error: one or more packages couldn't be built
```

Calling the idris compiler directly works:

```
$ idris --codegen javascript src/Main.idr -o test.js
$ node test.js 
Hello world!
```

Project is attached, any pointers?

[test.zip](https://github.com/elba/elba/files/3495235/test.zip)

**Comment by andylokandy** [comment]
Unfortunately elba doesn't read backend section from `elba.toml`. You can only pass it from cli args like `elba build --backend javascript`

**Comment by mixedCase** [comment]
Thanks for the workaround, changed to a more useful title for trackign the issue.

**Comment by andylokandy** [comment]
I am going to close this issue. 

@dcao expressed his concern on a potential problem that the user of the library may have different codegen backend setup from the libarary author's, so we should not allow the author from specifying the backend to use.

At lease one thing I think we can do later is to change the manifest parser to be more conservative so that it could throw an error when a unsupported section or item is provided.

**Comment by mixedCase** [comment]
I think being able to specify the codegen for binary targets only would be a really nice to have so that `elba build` works out of the box, after all, `main` will always target a specific `IO'` implementation.

**Comment by andylokandy** [comment]
Sounds good to me, but it may not be done until next major release because it involves fundamental changes on build system.
